import React from 'react'

export default function About() {
  return (
    <div className='bg-red-300 py-3 mt-5 h-screen '>About page
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum cum repellendus at laboriosam dicta molestiae ducimus ratione accusamus nulla? Quasi eius iusto praesentium. Maiores quisquam perspiciatis excepturi cupiditate, quibusdam aperiam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut impedit praesentium eum maxime facere eos placeat repellat magni, quos nisi error saepe inventore explicabo dignissimos accusantium numquam eligendi. Vitae, adipisci eum alias et exercitationem veritatis possimus, soluta praesentium similique repudiandae fugit doloribus repellendus accusamus nobis unde beatae est mollitia. Vel officiis amet dolore voluptatem velit distinctio fugiat, quisquam odit quo, aut autem quos. Iusto est quis eius eaque quisquam atque ut magni consequatur placeat velit, aperiam facilis reiciendis, dignissimos repellat accusamus debitis non. Ullam quo, autem, distinctio reiciendis quaerat earum, tempore sunt itaque corrupti possimus consequuntur! Voluptatibus perferendis, doloremque temporibus eius obcaecati assumenda veniam culpa eos inventore tenetur praesentium consequuntur dolor voluptatem sapiente est. Quod ab dignissimos sunt ullam ipsum nostrum blanditiis, temporibus et facilis deserunt repellat voluptate consequatur rem commodi consectetur cupiditate quaerat, perspiciatis repudiandae odio illum. Distinctio officia, quod ad est qui a accusamus ipsum. Aut assumenda nesciunt aliquam repellat similique sed esse nam harum nemo quos rerum id sunt nulla, fugiat dolor obcaecati maiores nisi delectus odio temporibus dolore. Laborum consequuntur ipsa dolores nulla impedit. Vitae inventore aliquid quam officiis earum, eum at perferendis, quia ipsa, quos enim beatae voluptas dolorum reprehenderit dignissimos! Voluptatem temporibus beatae pariatur.
    </div>
  )
}
